services:
  mysql:
    image: mariadb:10.11.10
    logging:
      driver: none
    command: ["--max-allowed-packet=512M"]
    volumes:
      - "./data/db:/var/lib/mysql:delegated"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    restart: always
    ports:
      - "3306:3306"
    networks:
      - default
  test1_local:
    image: litespeedtech/openlitespeed:${OLS_VERSION}-${PHP_VERSION}
    container_name: test1_local
    env_file:
      - .env
    volumes:
      - ./test1_local/lsws/conf:/usr/local/lsws/conf
      - ./test1_local/lsws/admin-conf:/usr/local/lsws/admin/conf
      - ./bin/container:/usr/local/bin
      - ./test1_local/sites:/var/www/vhosts/
      - ./test1_local/acme:/root/.acme.sh/
      - ./test1_local/logs:/usr/local/lsws/logs/
    restart: always
    environment:
      TZ: ${TimeZone}
    networks:
      - default
  allinoneplaza_com:
    image: litespeedtech/openlitespeed:${OLS_VERSION}-${PHP_VERSION}
    container_name: allinoneplaza_com
    env_file:
      - .env
    volumes:
      - ./allinoneplaza_com/lsws/conf:/usr/local/lsws/conf
      - ./allinoneplaza_com/lsws/admin-conf:/usr/local/lsws/admin/conf
      - ./bin/container:/usr/local/bin
      - ./allinoneplaza_com/sites:/var/www/vhosts/
      - ./allinoneplaza_com/acme:/root/.acme.sh/
      - ./allinoneplaza_com/logs:/usr/local/lsws/logs/
    restart: always
    environment:
      TZ: ${TimeZone}
    networks:
      - default
  nginx:
      build:
        context: ./nginx
        args:
          - CHANGE_SOURCE=${CHANGE_SOURCE}
          - http_proxy
          - https_proxy
          - no_proxy
      volumes:
        - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
        - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
        - ${NGINX_SSL_PATH}:/etc/nginx/ssl
      ports:
        - "${NGINX_HOST_HTTP_PORT}:80"
        - "${NGINX_HOST_HTTPS_PORT}:443"
        - "${VARNISH_BACKEND_PORT}:81"
      depends_on:
        - test1_local
      networks:
        - default
  phpmyadmin:
    image: bitnami/phpmyadmin:5.2.0-debian-11-r43
    ports:
      - 8081:8080
      - 8441:8443
    environment:
        DATABASE_HOST: mysql
    restart: always
    networks:
      - default
  redis:
    image: "redis:alpine"
    logging:
      driver: none
    # command: redis-server --requirepass 8b405f60665e48f795752e534d93b722
    volumes:
      - ./redis/data:/var/lib/redis
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master
    restart: always
    networks:
      - default
networks:
  default:
    driver: bridge
